---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: concourse
  namespace: hivemind
...

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: concourse-hivemind-admin
  namespace: hivemind

subjects:
  - kind: ServiceAccount
    name: concourse
    namespace: hivemind

roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
...
