---
resources:
  - name: hivemind-src
    type: git
    icon: git
    source:
      uri: https://github.com/tlwr/hivemind.git
      branch: main


jobs:
  - name: test
    serial: true
    public: true
    plan:
      - get: hivemind-src
        trigger: true

      - task: test
        privileged: true
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: ruby

          inputs:
            - name: hivemind-src
              path: .

          run:
            path: sh
            args:
              - -c
              - |
                make deps
                make test
